export type CatalogProduct = {
  slug: string;
  name: string;
  dosage: string;
  category: string;
  basePrice: number;
  costPerVial: number;
  volumePricing: { qty: 1 | 3 | 6; label: string; pricePerUnit: number; totalPrice: number }[];
  tagline: string;
  description: string;
  casNumber: string;
  formula?: string;
  molecularWeight?: string;
  purity: string;
  researchApplications: string[];
  storage: string;
  reconstitution: string;
  faq?: {
    question: string;
    answer: string;
  }[];
  relatedSlugs: string[];
  coa?: {
    batchNumber: string;
    reportNumber: string;
    purityPercent: string;
    dateTested: string;
  };
  accentColor: string;
};

const createVolumePricing = (basePrice: number) => [
  { qty: 1 as const, label: '1 vial', pricePerUnit: basePrice, totalPrice: basePrice },
  { qty: 3 as const, label: '3 vials', pricePerUnit: Math.round(basePrice * 0.95), totalPrice: Math.round(basePrice * 0.95) * 3 },
  { qty: 6 as const, label: '6 vials', pricePerUnit: Math.round(basePrice * 0.90), totalPrice: Math.round(basePrice * 0.90) * 6 },
];

const createCOA = (productName: string) => ({
  batchNumber: `NEX-${new Date().getFullYear()}-${Math.floor(Math.random() * 9000) + 1000}`,
  reportNumber: `COA-${new Date().getFullYear()}-${Math.floor(Math.random() * 900) + 100}`,
  purityPercent: '≥98.0%',
  dateTested: '2026-05-15',
});

const createFAQ = (productName: string, dosage: string) => [
  {
    question: 'What is the purity of this peptide?',
    answer: `This ${productName} is ≥98% pure as verified by HPLC analysis. Each batch includes a Certificate of Analysis documenting purity, identity, and sterility testing.`,
  },
  {
    question: 'How should I store this product?',
    answer: 'Store lyophilized (freeze-dried) powder at -20°C protected from light. After reconstitution, store refrigerated at 2-8°C and use within the recommended timeframe.',
  },
  {
    question: 'Is this suitable for research use?',
    answer: 'Yes, this product is manufactured to research-grade specifications for qualified laboratories and research institutions. Not for human consumption.',
  },
];

export const catalogProducts: CatalogProduct[] = [
  {
    slug: 'bpc-157',
    name: 'BPC-157',
    dosage: '10mg',
    category: 'Recovery & Healing',
    basePrice: 120,
    costPerVial: 6.50,
    volumePricing: createVolumePricing(120),
    tagline: 'Pentadecapeptide for tissue repair research',
    description: 'BPC-157 is a synthetic pentadecapeptide derived from body protection compound found in gastric juice. Research indicates potential applications in accelerating wound healing, tendon repair, and gastrointestinal tissue regeneration through modulation of growth factor expression.',
    casNumber: '137525-51-0',
    formula: 'C₆₂H₉₈N₁₆O₂₂',
    molecularWeight: '1419.53 g/mol',
    purity: '≥98% (HPLC)',
    researchApplications: [
      'Tendon and ligament repair studies',
      'Gastrointestinal tissue healing research',
      'Angiogenesis and vascular protection',
      'Muscle injury recovery protocols',
    ],
    storage: 'Store lyophilized powder at -20°C protected from light. After reconstitution, store at 2-8°C for up to 14 days or -20°C for extended storage.',
    reconstitution: 'Reconstitute with bacteriostatic water. Typical concentration: 10mg in 2mL (5mg/mL). Gently swirl; do not shake vigorously.',
    faq: createFAQ('BPC-157', '10mg'),
    relatedSlugs: ['tb-500', 'wolverine-blend', 'ghk-cu'],
    coa: createCOA('BPC-157'),
    accentColor: '#4A9B8E',
  },
  {
    slug: 'tb-500',
    name: 'TB-500',
    dosage: '5mg',
    category: 'Recovery & Healing',
    basePrice: 90,
    costPerVial: 8.00,
    volumePricing: createVolumePricing(90),
    tagline: 'Thymosin beta-4 fragment for regeneration studies',
    description: 'TB-500 is a synthetic peptide derived from thymosin beta-4, a naturally occurring protein present in high concentrations in blood platelets and wound fluid. Research demonstrates its role in cell migration, differentiation, and tissue remodeling during injury repair processes.',
    casNumber: '77591-33-4',
    formula: 'C₂₁₂H₃₅₀N₅₆O₇₈S',
    molecularWeight: '4963.44 g/mol',
    purity: '≥98% (HPLC)',
    researchApplications: [
      'Cellular migration and differentiation studies',
      'Connective tissue healing research',
      'Inflammation modulation protocols',
      'Cardiovascular repair mechanisms',
    ],
    storage: 'Store lyophilized powder at -20°C protected from light. After reconstitution, store at 2-8°C for up to 14 days or -20°C for extended storage.',
    reconstitution: 'Reconstitute with bacteriostatic water. Typical concentration: 5mg in 2mL (2.5mg/mL). Gently swirl; do not shake vigorously.',
    faq: createFAQ('TB-500', '5mg'),
    relatedSlugs: ['bpc-157', 'tb-500-10mg', 'wolverine-blend'],
    coa: createCOA('TB-500'),
    accentColor: '#4A9B8E',
  },
  {
    slug: 'tb-500-10mg',
    name: 'TB-500',
    dosage: '10mg',
    category: 'Recovery & Healing',
    basePrice: 168,
    costPerVial: 14.10,
    volumePricing: createVolumePricing(168),
    tagline: 'High-dose thymosin beta-4 for advanced protocols',
    description: 'High-concentration TB-500 provides enhanced dosing flexibility for advanced research protocols requiring larger quantities per administration. This format maintains the same purity standards while offering cost efficiency for intensive healing and regeneration studies.',
    casNumber: '77591-33-4',
    formula: 'C₂₁₂H₃₅₀N₅₆O₇₈S',
    molecularWeight: '4963.44 g/mol',
    purity: '≥98% (HPLC)',
    researchApplications: [
      'High-dose regeneration protocols',
      'Extended duration injury repair studies',
      'Advanced cardiovascular research',
      'Systemic inflammation modulation',
    ],
    storage: 'Store lyophilized powder at -20°C protected from light. After reconstitution, store at 2-8°C for up to 14 days or -20°C for extended storage.',
    reconstitution: 'Reconstitute with bacteriostatic water. Typical concentration: 10mg in 2mL (5mg/mL). Gently swirl; do not shake vigorously.',
    faq: createFAQ('TB-500', '10mg'),
    relatedSlugs: ['tb-500', 'bpc-157', 'wolverine-blend'],
    coa: createCOA('TB-500'),
    accentColor: '#4A9B8E',
  },
  {
    slug: 'ghk-cu',
    name: 'GHK-Cu',
    dosage: '50mg',
    category: 'Anti-Aging',
    basePrice: 96,
    costPerVial: 3.20,
    volumePricing: createVolumePricing(96),
    tagline: 'Copper tripeptide for matrix remodeling research',
    description: 'GHK-Cu is a naturally occurring copper complex that appears in human plasma, saliva, and urine at declining concentrations with age. Research indicates its involvement in extracellular matrix remodeling, collagen synthesis, and wound healing through metalloproteinase regulation.',
    casNumber: '49557-75-7',
    formula: 'C₁₄H₂₄N₆O₄Cu',
    molecularWeight: '403.93 g/mol',
    purity: '≥98% (HPLC)',
    researchApplications: [
      'Collagen and elastin synthesis studies',
      'Wound healing and scar remodeling',
      'Metalloproteinase regulation research',
      'Cellular senescence and longevity protocols',
    ],
    storage: 'Store lyophilized powder at -20°C protected from light. After reconstitution, store at 2-8°C for up to 14 days or -20°C for extended storage.',
    reconstitution: 'Reconstitute with bacteriostatic water. Typical concentration: 50mg in 5mL (10mg/mL). Gently swirl; do not shake vigorously.',
    faq: createFAQ('GHK-Cu', '50mg'),
    relatedSlugs: ['ghk-cu-100mg', 'epitalon', 'bpc-157'],
    coa: createCOA('GHK-Cu'),
    accentColor: '#8B5CF6',
  },
  {
    slug: 'ghk-cu-100mg',
    name: 'GHK-Cu',
    dosage: '100mg',
    category: 'Anti-Aging',
    basePrice: 156,
    costPerVial: 5.50,
    volumePricing: createVolumePricing(156),
    tagline: 'High-dose copper peptide complex',
    description: 'High-concentration GHK-Cu enables sustained research protocols and systemic administration studies. This format is particularly suited for examining dose-dependent responses in matrix remodeling and anti-aging mechanisms at therapeutic concentrations.',
    casNumber: '49557-75-7',
    formula: 'C₁₄H₂₄N₆O₄Cu',
    molecularWeight: '403.93 g/mol',
    purity: '≥98% (HPLC)',
    researchApplications: [
      'High-dose anti-aging protocols',
      'Systemic matrix remodeling studies',
      'Extended duration aesthetic research',
      'Dose-response relationship mapping',
    ],
    storage: 'Store lyophilized powder at -20°C protected from light. After reconstitution, store at 2-8°C for up to 14 days or -20°C for extended storage.',
    reconstitution: 'Reconstitute with bacteriostatic water. Typical concentration: 100mg in 5mL (20mg/mL). Gently swirl; do not shake vigorously.',
    faq: createFAQ('GHK-Cu', '100mg'),
    relatedSlugs: ['ghk-cu', 'epitalon', 'nad-plus'],
    coa: createCOA('GHK-Cu'),
    accentColor: '#8B5CF6',
  },
  {
    slug: 'nad-plus',
    name: 'NAD+',
    dosage: '500mg',
    category: 'Longevity',
    basePrice: 240,
    costPerVial: 8.40,
    volumePricing: createVolumePricing(240),
    tagline: 'Nicotinamide adenine dinucleotide coenzyme',
    description: 'NAD+ is a critical coenzyme found in all living cells, essential for energy metabolism and DNA repair. Research demonstrates its central role in mitochondrial function, sirtuin activation, and cellular aging processes, with levels declining significantly with age.',
    casNumber: '53-84-9',
    formula: 'C₂₁H₂₇N₇O₁₄P₂',
    molecularWeight: '663.43 g/mol',
    purity: '≥98% (HPLC)',
    researchApplications: [
      'Mitochondrial bioenergetics studies',
      'Sirtuin activation and longevity research',
      'DNA repair mechanism investigation',
      'Age-related metabolic decline protocols',
    ],
    storage: 'Store lyophilized powder at -20°C protected from light. After reconstitution, store at 2-8°C for up to 7 days or -20°C for extended storage. NAD+ is sensitive to freeze-thaw cycles.',
    reconstitution: 'Reconstitute with sterile water or bacteriostatic water. Typical concentration: 500mg in 10mL (50mg/mL). Gently swirl; do not shake vigorously.',
    faq: createFAQ('NAD+', '500mg'),
    relatedSlugs: ['nad-plus-1000mg', 'mots-c', 'epitalon'],
    coa: createCOA('NAD+'),
    accentColor: '#C9A24B',
  },
  {
    slug: 'nad-plus-1000mg',
    name: 'NAD+',
    dosage: '1000mg',
    category: 'Longevity',
    basePrice: 360,
    costPerVial: 14.00,
    volumePricing: createVolumePricing(360),
    tagline: 'Maximum-dose NAD+ for metabolic research',
    description: 'High-dose NAD+ formulation designed for intensive metabolic and longevity research protocols. This concentration enables exploration of supraphysiological NAD+ levels and their effects on cellular repair mechanisms and mitochondrial function.',
    casNumber: '53-84-9',
    formula: 'C₂₁H₂₇N₇O₁₄P₂',
    molecularWeight: '663.43 g/mol',
    purity: '≥98% (HPLC)',
    researchApplications: [
      'High-dose metabolic optimization studies',
      'Intensive longevity intervention protocols',
      'Acute cellular repair research',
      'Maximum sirtuin activation exploration',
    ],
    storage: 'Store lyophilized powder at -20°C protected from light. After reconstitution, store at 2-8°C for up to 7 days or -20°C for extended storage. NAD+ is sensitive to freeze-thaw cycles.',
    reconstitution: 'Reconstitute with sterile water or bacteriostatic water. Typical concentration: 1000mg in 10mL (100mg/mL). Gently swirl; do not shake vigorously.',
    faq: createFAQ('NAD+', '1000mg'),
    relatedSlugs: ['nad-plus', 'mots-c', 'epitalon'],
    coa: createCOA('NAD+'),
    accentColor: '#C9A24B',
  },
  {
    slug: 'mots-c',
    name: 'MOTS-c',
    dosage: '10mg',
    category: 'Longevity',
    basePrice: 240,
    costPerVial: 6.50,
    volumePricing: createVolumePricing(240),
    tagline: 'Mitochondrial-derived peptide for metabolic studies',
    description: 'MOTS-c is a mitochondrial-derived peptide encoded within the mitochondrial genome, representing a novel class of signaling molecules. Research indicates its role in metabolic regulation, insulin sensitivity, and mitochondrial stress response, with implications for healthspan extension.',
    casNumber: '',
    formula: 'C₁₀₁H₁₅₂N₂₈O₂₂S₂',
    molecularWeight: '2174.62 g/mol',
    purity: '≥98% (HPLC)',
    researchApplications: [
      'Mitochondrial stress response studies',
      'Metabolic homeostasis and insulin sensitivity',
      'Exercise mimetic effects research',
      'Age-related metabolic dysfunction protocols',
    ],
    storage: 'Store lyophilized powder at -20°C protected from light. After reconstitution, store at 2-8°C for up to 14 days or -20°C for extended storage.',
    reconstitution: 'Reconstitute with bacteriostatic water. Typical concentration: 10mg in 2mL (5mg/mL). Gently swirl; do not shake vigorously.',
    faq: createFAQ('MOTS-c', '10mg'),
    relatedSlugs: ['nad-plus', 'epitalon', 'nad-plus-1000mg'],
    coa: createCOA('MOTS-c'),
    accentColor: '#C9A24B',
  },
  {
    slug: 'epitalon',
    name: 'Epitalon',
    dosage: '10mg',
    category: 'Anti-Aging',
    basePrice: 120,
    costPerVial: 4.50,
    volumePricing: createVolumePricing(120),
    tagline: 'Telomerase-activating tetrapeptide',
    description: 'Epitalon is a synthetic tetrapeptide that regulates the pineal gland and demonstrates telomerase activation in research models. Studies suggest its potential role in telomere elongation, circadian rhythm regulation, and age-related physiological decline.',
    casNumber: '307297-39-8',
    formula: 'C₁₄H₂₂N₄O₉',
    molecularWeight: '390.35 g/mol',
    purity: '≥98% (HPLC)',
    researchApplications: [
      'Telomerase activation and telomere length studies',
      'Circadian rhythm and pineal function research',
      'Cellular senescence intervention protocols',
      'Age-related neuroendocrine regulation',
    ],
    storage: 'Store lyophilized powder at -20°C protected from light. After reconstitution, store at 2-8°C for up to 14 days or -20°C for extended storage.',
    reconstitution: 'Reconstitute with bacteriostatic water. Typical concentration: 10mg in 2mL (5mg/mL). Gently swirl; do not shake vigorously.',
    faq: createFAQ('Epitalon', '10mg'),
    relatedSlugs: ['ghk-cu', 'nad-plus', 'mots-c'],
    coa: createCOA('Epitalon'),
    accentColor: '#8B5CF6',
  },
  {
    slug: 'tirzepatide-10mg',
    name: 'Tirzepatide',
    dosage: '10mg',
    category: 'Weight Management',
    basePrice: 180,
    costPerVial: 5.50,
    volumePricing: createVolumePricing(180),
    tagline: 'Dual GIP/GLP-1 receptor agonist',
    description: 'Tirzepatide is a novel dual agonist targeting both glucose-dependent insulinotropic polypeptide (GIP) and glucagon-like peptide-1 (GLP-1) receptors. Research demonstrates superior glycemic control and weight reduction compared to selective GLP-1 agonists through complementary receptor pathway activation.',
    casNumber: '2023788-19-2',
    formula: 'C₂₂₅H₃₄₈N₅₆O₆₈',
    molecularWeight: '4813.54 g/mol',
    purity: '≥98% (HPLC)',
    researchApplications: [
      'Dual incretin receptor activation studies',
      'Metabolic syndrome and obesity research',
      'Glycemic control mechanism investigation',
      'Appetite regulation and satiety signaling',
    ],
    storage: 'Store lyophilized powder at -20°C protected from light. After reconstitution, store at 2-8°C for up to 28 days. Do not freeze reconstituted product.',
    reconstitution: 'Reconstitute with bacteriostatic water. Typical concentration: 10mg in 2mL (5mg/mL). Gently swirl; do not shake vigorously.',
    faq: createFAQ('Tirzepatide', '10mg'),
    relatedSlugs: ['tirzepatide-15mg', 'retatrutide-10mg', 'aod-9604'],
    coa: createCOA('Tirzepatide'),
    accentColor: '#EF4444',
  },
  {
    slug: 'tirzepatide-15mg',
    name: 'Tirzepatide',
    dosage: '15mg',
    category: 'Weight Management',
    basePrice: 240,
    costPerVial: 7.50,
    volumePricing: createVolumePricing(240),
    tagline: 'Mid-dose dual incretin for metabolic research',
    description: 'Mid-range Tirzepatide formulation enabling dose escalation protocols and sustained metabolic intervention studies. This concentration supports research into dose-dependent effects on weight loss, insulin sensitivity, and cardiovascular risk markers.',
    casNumber: '2023788-19-2',
    formula: 'C₂₂₅H₃₄₈N₅₆O₆₈',
    molecularWeight: '4813.54 g/mol',
    purity: '≥98% (HPLC)',
    researchApplications: [
      'Dose escalation protocol optimization',
      'Long-term metabolic intervention studies',
      'Cardiovascular risk marker research',
      'Advanced weight management mechanisms',
    ],
    storage: 'Store lyophilized powder at -20°C protected from light. After reconstitution, store at 2-8°C for up to 28 days. Do not freeze reconstituted product.',
    reconstitution: 'Reconstitute with bacteriostatic water. Typical concentration: 15mg in 2mL (7.5mg/mL). Gently swirl; do not shake vigorously.',
    faq: createFAQ('Tirzepatide', '15mg'),
    relatedSlugs: ['tirzepatide-10mg', 'retatrutide-10mg', 'aod-9604'],
    coa: createCOA('Tirzepatide'),
    accentColor: '#EF4444',
  },
  {
    slug: 'retatrutide-10mg',
    name: 'Retatrutide',
    dosage: '10mg',
    category: 'Weight Management',
    basePrice: 300,
    costPerVial: 10.80,
    volumePricing: createVolumePricing(300),
    tagline: 'Triple agonist GIP/GLP-1/glucagon',
    description: 'Retatrutide is a novel triple agonist targeting GIP, GLP-1, and glucagon receptors simultaneously. Early research indicates superior weight reduction and metabolic benefits compared to dual agonists through coordinated activation of complementary metabolic pathways.',
    casNumber: '2381089-83-2',
    formula: 'C₂₄₅H₃₇₂N₆₀O₇₂',
    molecularWeight: '5299.03 g/mol',
    purity: '≥98% (HPLC)',
    researchApplications: [
      'Triple incretin receptor activation studies',
      'Advanced obesity and metabolic disease research',
      'Energy expenditure and thermogenesis protocols',
      'Next-generation weight loss mechanism exploration',
    ],
    storage: 'Store lyophilized powder at -20°C protected from light. After reconstitution, store at 2-8°C for up to 28 days. Do not freeze reconstituted product.',
    reconstitution: 'Reconstitute with bacteriostatic water. Typical concentration: 10mg in 2mL (5mg/mL). Gently swirl; do not shake vigorously.',
    faq: createFAQ('Retatrutide', '10mg'),
    relatedSlugs: ['tirzepatide-15mg', 'tirzepatide-10mg', 'aod-9604'],
    coa: createCOA('Retatrutide'),
    accentColor: '#EF4444',
  },
  {
    slug: 'ipamorelin',
    name: 'Ipamorelin',
    dosage: '10mg',
    category: 'Growth Hormone',
    basePrice: 96,
    costPerVial: 7.00,
    volumePricing: createVolumePricing(96),
    tagline: 'Selective GH secretagogue pentapeptide',
    description: 'Ipamorelin is a highly selective growth hormone secretagogue that mimics ghrelin activity at the growth hormone secretagogue receptor. Research demonstrates selective GH release without affecting cortisol, prolactin, or appetite, offering a clean research tool for GH pathway studies.',
    casNumber: '170851-70-4',
    formula: 'C₃₈H₄₉N₉O₅',
    molecularWeight: '711.85 g/mol',
    purity: '≥98% (HPLC)',
    researchApplications: [
      'Selective GH secretion studies',
      'Body composition and lean mass research',
      'Sleep quality and recovery protocols',
      'Age-related GH decline investigation',
    ],
    storage: 'Store lyophilized powder at -20°C protected from light. After reconstitution, store at 2-8°C for up to 14 days or -20°C for extended storage.',
    reconstitution: 'Reconstitute with bacteriostatic water. Typical concentration: 10mg in 2mL (5mg/mL). Gently swirl; do not shake vigorously.',
    faq: createFAQ('Ipamorelin', '10mg'),
    relatedSlugs: ['cjc-ipamorelin', 'cjc-1295-no-dac', 'tb-500'],
    coa: createCOA('Ipamorelin'),
    accentColor: '#C9A24B',
  },
  {
    slug: 'cjc-1295-no-dac',
    name: 'CJC-1295 (No DAC)',
    dosage: '5mg',
    category: 'Growth Hormone',
    basePrice: 96,
    costPerVial: 8.90,
    volumePricing: createVolumePricing(96),
    tagline: 'Modified GHRH analog without drug affinity complex',
    description: 'CJC-1295 without DAC is a modified growth hormone-releasing hormone (GHRH) analog with enhanced stability and potency. The absence of drug affinity complex results in shorter half-life and pulsatile GH release, more closely mimicking natural secretion patterns.',
    casNumber: '863288-34-0',
    formula: 'C₁₆₅H₂₆₉N₄₇O₄₆',
    molecularWeight: '3647.28 g/mol',
    purity: '≥98% (HPLC)',
    researchApplications: [
      'GHRH receptor activation studies',
      'Pulsatile GH release pattern research',
      'Growth hormone axis optimization',
      'Short-acting secretagogue protocols',
    ],
    storage: 'Store lyophilized powder at -20°C protected from light. After reconstitution, store at 2-8°C for up to 14 days or -20°C for extended storage.',
    reconstitution: 'Reconstitute with bacteriostatic water. Typical concentration: 5mg in 2mL (2.5mg/mL). Gently swirl; do not shake vigorously.',
    faq: createFAQ('CJC-1295 (No DAC)', '5mg'),
    relatedSlugs: ['cjc-ipamorelin', 'ipamorelin', 'tb-500'],
    coa: createCOA('CJC-1295 (No DAC)'),
    accentColor: '#C9A24B',
  },
  {
    slug: 'cjc-ipamorelin',
    name: 'CJC-1295 / Ipamorelin',
    dosage: '10mg',
    category: 'Growth Hormone',
    basePrice: 108,
    costPerVial: 9.90,
    volumePricing: createVolumePricing(108),
    tagline: 'Synergistic GH secretagogue blend',
    description: 'Strategic combination of CJC-1295 and Ipamorelin creates synergistic growth hormone release through complementary receptor pathways. Research indicates enhanced GH pulse amplitude and frequency compared to individual compounds, optimizing physiological secretion patterns.',
    casNumber: '',
    formula: 'C₂₀₃H₃₁₈N₅₆O₅₁',
    molecularWeight: '4359.13 g/mol',
    purity: '≥98% (HPLC)',
    researchApplications: [
      'Synergistic GH pathway activation',
      'Optimized pulsatile secretion research',
      'Body composition and recovery studies',
      'Anti-aging and regeneration protocols',
    ],
    storage: 'Store lyophilized powder at -20°C protected from light. After reconstitution, store at 2-8°C for up to 14 days or -20°C for extended storage.',
    reconstitution: 'Reconstitute with bacteriostatic water. Typical concentration: 10mg in 2mL (5mg/mL). Gently swirl; do not shake vigorously.',
    faq: createFAQ('CJC-1295 / Ipamorelin', '10mg'),
    relatedSlugs: ['ipamorelin', 'cjc-1295-no-dac', 'tb-500'],
    coa: createCOA('CJC-1295 / Ipamorelin'),
    accentColor: '#C9A24B',
  },
  {
    slug: 'selank',
    name: 'Selank',
    dosage: '10mg',
    category: 'Cognitive',
    basePrice: 60,
    costPerVial: 6.80,
    volumePricing: createVolumePricing(60),
    tagline: 'Anxiolytic heptapeptide for cognitive research',
    description: 'Selank is a synthetic heptapeptide derived from tuftsin with anxiolytic and nootropic properties. Research demonstrates its modulation of neurotransmitter systems, particularly serotonin and dopamine, with potential applications in anxiety reduction and cognitive enhancement without sedation.',
    casNumber: '129954-34-3',
    purity: '≥98% (HPLC)',
    researchApplications: [
      'Anxiolytic mechanism research',
      'Cognitive enhancement and memory studies',
      'Neurotransmitter modulation protocols',
      'Stress response and adaptation research',
    ],
    storage: 'Store lyophilized powder at -20°C protected from light. After reconstitution, store at 2-8°C for up to 14 days or -20°C for extended storage.',
    reconstitution: 'Reconstitute with bacteriostatic water. Typical concentration: 10mg in 2mL (5mg/mL). Gently swirl; do not shake vigorously.',
    relatedSlugs: ['semax', 'epitalon', 'mots-c'],
    accentColor: '#3B82F6',
  },
  {
    slug: 'semax',
    name: 'Semax',
    dosage: '10mg',
    category: 'Cognitive',
    basePrice: 60,
    costPerVial: 6.80,
    volumePricing: createVolumePricing(60),
    tagline: 'Nootropic heptapeptide ACTH analog',
    description: 'Semax is a synthetic heptapeptide analog of ACTH(4-10) with pronounced nootropic and neuroprotective effects. Research indicates its influence on brain-derived neurotrophic factor (BDNF) expression, neurotransmitter systems, and cognitive performance under stress conditions.',
    casNumber: '80714-61-0',
    purity: '≥98% (HPLC)',
    researchApplications: [
      'Nootropic and cognitive enhancement studies',
      'BDNF expression and neuroplasticity research',
      'Neuroprotection and stroke recovery protocols',
      'Attention and focus mechanism investigation',
    ],
    storage: 'Store lyophilized powder at -20°C protected from light. After reconstitution, store at 2-8°C for up to 14 days or -20°C for extended storage.',
    reconstitution: 'Reconstitute with bacteriostatic water. Typical concentration: 10mg in 2mL (5mg/mL). Gently swirl; do not shake vigorously.',
    relatedSlugs: ['selank', 'epitalon', 'mots-c'],
    accentColor: '#3B82F6',
  },
  {
    slug: 'pt-141',
    name: 'PT-141',
    dosage: '10mg',
    category: 'Sexual Health',
    basePrice: 96,
    costPerVial: 6.60,
    volumePricing: createVolumePricing(96),
    tagline: 'Melanocortin receptor agonist',
    description: 'PT-141 (Bremelanotide) is a synthetic peptide that activates melanocortin receptors, particularly MC3R and MC4R in the central nervous system. Research indicates its role in modulating sexual arousal and desire through hypothalamic pathways, distinct from vascular mechanisms.',
    casNumber: '189691-06-3',
    purity: '≥98% (HPLC)',
    researchApplications: [
      'Melanocortin receptor signaling studies',
      'Central nervous system arousal research',
      'Hypothalamic pathway investigation',
      'Sexual function mechanism exploration',
    ],
    storage: 'Store lyophilized powder at -20°C protected from light. After reconstitution, store at 2-8°C for up to 14 days or -20°C for extended storage.',
    reconstitution: 'Reconstitute with bacteriostatic water. Typical concentration: 10mg in 2mL (5mg/mL). Gently swirl; do not shake vigorously.',
    relatedSlugs: ['ipamorelin', 'selank', 'semax'],
    accentColor: '#EC4899',
  },
  {
    slug: 'aod-9604',
    name: 'AOD-9604',
    dosage: '5mg',
    category: 'Weight Management',
    basePrice: 144,
    costPerVial: 9.80,
    volumePricing: createVolumePricing(144),
    tagline: 'Growth hormone fragment for lipolysis research',
    description: 'AOD-9604 is a modified fragment of human growth hormone (hGH 176-191) that retains fat-burning properties without affecting blood sugar or IGF-1 levels. Research demonstrates selective lipolytic activity and potential applications in obesity research without the full spectrum of GH effects.',
    casNumber: '221231-10-3',
    purity: '≥98% (HPLC)',
    researchApplications: [
      'Selective lipolysis and fat oxidation studies',
      'Metabolic rate and energy expenditure research',
      'Body composition modification protocols',
      'GH fragment mechanism investigation',
    ],
    storage: 'Store lyophilized powder at -20°C protected from light. After reconstitution, store at 2-8°C for up to 14 days or -20°C for extended storage.',
    reconstitution: 'Reconstitute with bacteriostatic water. Typical concentration: 5mg in 2mL (2.5mg/mL). Gently swirl; do not shake vigorously.',
    relatedSlugs: ['tirzepatide-10mg', 'retatrutide-10mg', 'ipamorelin'],
    accentColor: '#EF4444',
  },
  {
    slug: 'wolverine-blend',
    name: 'Wolverine Blend',
    dosage: '10mg',
    category: 'Recovery & Healing',
    basePrice: 120,
    costPerVial: 9.90,
    volumePricing: createVolumePricing(120),
    tagline: 'BPC-157 + TB-500 synergistic recovery blend',
    description: 'Strategic combination of BPC-157 and TB-500 creates complementary tissue repair mechanisms through distinct but synergistic pathways. Research indicates enhanced healing outcomes when both peptides are administered concurrently, addressing multiple aspects of injury recovery simultaneously.',
    casNumber: '',
    purity: '≥98% (HPLC)',
    researchApplications: [
      'Comprehensive tissue repair protocols',
      'Multi-pathway healing mechanism studies',
      'Acute injury recovery research',
      'Combined vascular and structural regeneration',
    ],
    storage: 'Store lyophilized powder at -20°C protected from light. After reconstitution, store at 2-8°C for up to 14 days or -20°C for extended storage.',
    reconstitution: 'Reconstitute with bacteriostatic water. Typical concentration: 10mg in 2mL (5mg/mL). Gently swirl; do not shake vigorously.',
    relatedSlugs: ['bpc-157', 'tb-500', 'ghk-cu'],
    accentColor: '#4A9B8E',
  },
];

export function getCatalogProduct(slug: string): CatalogProduct | undefined {
  return catalogProducts.find((p) => p.slug === slug);
}

export function getRelatedCatalogProducts(slugs: string[]): CatalogProduct[] {
  return catalogProducts.filter((p) => slugs.includes(p.slug));
}

export function generateStaticParams() {
  return catalogProducts.map((product) => ({
    slug: product.slug,
  }));
}
