import type { BlogArticle } from '../blog-types';

export const article: BlogArticle = {
  slug: "mt-2-melanotan-ii-melanocortin-research-review",
  title: "Melanotan II (MT-2) Research Review: Melanocortin Pharmacology, Models, and Study Design",
  description:
    "A comprehensive research review of Melanotan II (MT-2) — covering structure and receptor selectivity vs. PT-141, melanogenesis mechanisms, photoprotection models, published pharmacokinetic data, dose-response relationships, and key experimental design considerations for researchers studying MC1R and MC4R biology.",
  category: "Compound Profiles",
  readMinutes: 10,
  publishedAt: "2026-06-06",
  ogImage: "/og-image.jpg",
  body: [
    {
      type: "paragraph",
      text: "Melanotan II (MT-2; CAS 121062-08-6) is a synthetic cyclic analogue of the endogenous tridecapeptide α-melanocyte-stimulating hormone (α-MSH). Originally developed at the University of Arizona in the 1980s–1990s, MT-2 was designed to capitalize on the observation that α-MSH and its truncated analogues could stimulate melanogenesis with greater potency and receptor selectivity than the native hormone, while maintaining the cyclic lactam configuration that confers metabolic stability.",
    },
    {
      type: "paragraph",
      text: "MT-2 remains one of the most studied melanocortin peptides in preclinical literature, with research spanning skin biology, energy metabolism, sexual behavior, addiction circuitry, and neuroprotection. Its broad melanocortin receptor activity — with documented agonism at MC1R, MC3R, MC4R, and MC5R — makes it both a pharmacologically rich research tool and a compound requiring careful receptor-attribution controls in study design.",
    },
    {
      type: "heading",
      text: "Structure and Receptor Binding Profile",
    },
    {
      type: "paragraph",
      text: "MT-2's structure is: Ac-Nle-cyclo[Asp-His-D-Phe-Arg-Trp-Lys]-NH₂. MW = 1024.2 g/mol. The cyclic lactam bridge between Asp³ and Lys¹⁰ is the critical structural feature that provides metabolic stability (half-life ~3–4 hours in vivo vs. ~15 minutes for linear α-MSH) and pan-melanocortin receptor activity. The D-Phe substitution at position 7 enhances receptor binding affinity approximately 100-fold over α-MSH.",
    },
    {
      type: "paragraph",
      text: "Compared to PT-141 (bremelanotide), which lacks the C-terminal amide and shows reduced MC1R activity, MT-2 retains strong MC1R agonism alongside its MC3R and MC4R activity. This structural difference has significant practical consequences for experimental design: MT-2 studies must account for MC1R-mediated melanogenesis as a potential confound or co-endpoint in any behavioral or metabolic study, whereas PT-141 studies have a reduced (though not eliminated) pigmentation signal.",
    },
    {
      type: "table",
      headers: ["Receptor", "MT-2 Ki (nM)", "PT-141 Ki (nM)", "Primary Tissue Function"],
      rows: [
        ["MC1R", "~0.3", "~10", "Melanocyte eumelanin synthesis, UV photoprotection"],
        ["MC2R", ">1000", ">1000", "ACTH receptor; not relevant for these peptides"],
        ["MC3R", "~5", "~2", "CNS energy balance, limbic behavior, anti-inflammatory"],
        ["MC4R", "~1.5", "~1.5", "Hypothalamic energy expenditure, sexual behavior, autonomic tone"],
        ["MC5R", "~15", "~25", "Exocrine gland secretion, sebaceous function"],
      ],
    },
    {
      type: "heading",
      text: "Melanogenesis: The MC1R Pathway",
    },
    {
      type: "subheading",
      text: "Cellular Mechanism",
    },
    {
      type: "paragraph",
      text: "MC1R is a Gs-coupled GPCR expressed predominantly on epidermal melanocytes. Activation by MT-2 (or endogenous α-MSH) triggers adenylyl cyclase-mediated cAMP elevation, which activates protein kinase A (PKA). PKA phosphorylates and activates CREB (cAMP response element-binding protein), which in turn drives transcription of MITF (microphthalmia-associated transcription factor). MITF is the master regulator of melanogenic gene expression, upregulating tyrosinase (TYR), tyrosinase-related protein 1 (TYRP1), and DCT (dopachrome tautomerase) — the enzymatic machinery of the melanin biosynthesis pathway.",
    },
    {
      type: "paragraph",
      text: "The net result is increased eumelanin production in melanocytes, transfer of melanosomes to surrounding keratinocytes via melanosome transfer, and accumulation of eumelanin in the epidermis — producing visible skin darkening. Eumelanin is photoprotective: it absorbs UV-A and UV-B radiation and scavenges reactive oxygen species generated by UV exposure, reducing UV-induced DNA damage (cyclobutane pyrimidine dimers, 6-4 photoproducts) in keratinocytes.",
    },
    {
      type: "subheading",
      text: "Photoprotection Research Models",
    },
    {
      type: "paragraph",
      text: "MT-2 has been studied extensively in photoprotection models as a potential pharmacological approach to reducing UV-induced DNA damage. Key published work includes studies from the University of Arizona group showing that MT-2 pretreatment in pigmented and albino rodent models reduced UV-B-induced CPD formation per keratinocyte nucleus by 50–60% compared to vehicle controls — an effect that was MC1R-mediated and blocked by the specific MC1R antagonist Agouti-related protein (AgRP). Separately, in vitro studies on human melanocytes and reconstructed skin models have confirmed MT-2's dose-dependent upregulation of all three major melanogenic enzymes at nanomolar concentrations.",
    },
    {
      type: "heading",
      text: "Energy Metabolism and MC4R: The Metabolic Research Angle",
    },
    {
      type: "paragraph",
      text: "MC4R's role in energy homeostasis is among the best-characterized functions of the melanocortin system. MC4R knockout mice develop severe early-onset obesity — one of the most penetrant obesity phenotypes in rodent genetic models — and MC4R mutations are the single most common monogenic cause of human obesity (estimated ~3–5% of severely obese patients). MT-2's MC4R agonism therefore has direct relevance for metabolic researchers.",
    },
    {
      type: "paragraph",
      text: "Published rodent studies show that central or peripheral MT-2 administration acutely reduces food intake (hypophagia) and increases energy expenditure via sympathetic nervous system activation, brown adipose tissue thermogenesis, and locomotor activity increases. These effects are dose-dependent and can be fully blocked by SHU9119 (MC3R/MC4R antagonist), confirming MC4R as the primary mediator.",
    },
    {
      type: "list",
      items: [
        "Acute hypophagia: MT-2 at 0.01–1 mg/kg IP produces dose-dependent food intake reduction in fasted rats within 4 hours; ED50 approximately 0.03 mg/kg",
        "BAT thermogenesis: MT-2 activates UCP1 expression in brown adipose tissue via MC4R-sympathetic nerve axis; measurable increases in interscapular BAT temperature by telemetry at 0.1 mg/kg IV in rats",
        "Chronic administration effects: daily MT-2 (0.3 mg/kg SC) in high-fat-diet obese rats reduced body weight gain by ~15% over 4 weeks vs. vehicle; accompanied by reduced adiposity and improved insulin sensitivity",
        "Receptor mechanism: SHU9119 fully blocks food intake reduction and BAT activation, confirming MC3R/MC4R dependence; MC4R-specific HS014 blocks most but not all hypophagia, suggesting partial MC3R contribution",
      ],
    },
    {
      type: "heading",
      text: "Pharmacokinetics",
    },
    {
      type: "subheading",
      text: "Subcutaneous and IV Profiles",
    },
    {
      type: "paragraph",
      text: "MT-2 has well-characterized pharmacokinetics from Phase 1 and Phase 2 clinical development (it entered human trials before development was discontinued in favor of more selective compounds). Key pharmacokinetic parameters in humans (from SC dosing studies):",
    },
    {
      type: "list",
      items: [
        "SC bioavailability: ~95–100% relative to IV",
        "Tmax after SC: approximately 30–60 minutes",
        "Terminal half-life: 2.5–3.5 hours (vs. ~15 minutes for linear α-MSH)",
        "Volume of distribution: ~0.3–0.5 L/kg; modest CNS penetration via circumventricular organs and blood-brain barrier transport",
        "Clearance: predominantly proteolytic; no significant renal excretion of intact peptide; no relevant CYP450 involvement",
      ],
    },
    {
      type: "paragraph",
      text: "In rodent models, MT-2 pharmacokinetics follow similar patterns with proportionally shorter half-lives consistent with higher metabolic rates. Most behavioral and metabolic studies in rats use IP or SC injection 30–45 minutes prior to the experimental window to capture Cmax-proximate CNS exposure.",
    },
    {
      type: "heading",
      text: "Research Protocol Considerations",
    },
    {
      type: "subheading",
      text: "Dose Selection",
    },
    {
      type: "paragraph",
      text: "MT-2 dose selection must balance desired receptor engagement against side effect profiles that can confound behavioral endpoints:",
    },
    {
      type: "table",
      headers: ["Dose (rat, SC/IP)", "Primary Effects", "Side Effects to Monitor"],
      rows: [
        ["0.01–0.03 mg/kg", "Mild MC4R activation; hypophagia; minimal melanogenesis", "Blood pressure change; mild sedation"],
        ["0.1 mg/kg", "Moderate MC4R + MC3R; behavioral, metabolic, partial MC1R", "Yawning, stretching (penile erection model standard dose)"],
        ["0.3–0.5 mg/kg", "Full MC4R saturation; significant MC1R; strong behavioral", "Nausea analog (pica in rats), visible melanogenesis over days"],
        ["1.0 mg/kg", "Supra-maximal; non-specific; high side-effect burden", "Pica, hypertension, potential seizure threshold reduction at chronic use"],
      ],
    },
    {
      type: "subheading",
      text: "Key Experimental Controls",
    },
    {
      type: "paragraph",
      text: "Well-controlled MT-2 studies include:",
    },
    {
      type: "list",
      items: [
        "Vehicle-matched controls: 0.9% saline, same injection volume and route; MT-2 is typically dissolved in saline at 0.1–1 mg/mL",
        "Receptor antagonist groups: SHU9119 (1 mg/kg IP) 15 minutes prior to MT-2 to confirm MCR dependence; HS014 for MC4R-specific attribution",
        "Melanogenesis monitoring: daily or weekly photography of dorsal skin in pigmented rodents; use albino strains when melanogenesis is a confound for visual behavioral scoring",
        "Body temperature monitoring: MT-2 elevates core temperature via BAT activation; insert temperature telemetry or rectal probe time-course if temperature confounds are a concern",
        "Pica assessment (nausea model): kaolin ingestion as a non-emetic species nausea surrogate in rats; important for GI safety characterization",
        "Corticosterone measurement: collect terminal blood at consistent time points; MT-2 can activate HPA axis via MC4R in PVN; corticosterone differences between groups must be accounted for in stress-sensitive paradigms",
      ],
    },
    {
      type: "heading",
      text: "Differences Between MT-2 and α-MSH in Research Applications",
    },
    {
      type: "paragraph",
      text: "Researchers choosing between MT-2 and native α-MSH should understand key practical differences:",
    },
    {
      type: "list",
      items: [
        "Metabolic stability: MT-2 half-life ~3 hours vs. α-MSH ~15 minutes; MT-2 produces more sustained receptor activation per injection, more suitable for in vivo behavioral paradigms where prolonged exposure is needed",
        "Receptor breadth: α-MSH preferentially activates MC1R and MC3R at lower concentrations; MT-2's D-Phe substitution confers 100× greater affinity and broader receptor engagement",
        "MC1R potency: MT-2 is approximately 1000× more potent at MC1R than α-MSH on a molar basis, making it more suitable for melanogenesis research and photoprotection models where maximal melanocyte activation is needed",
        "CNS penetration: MT-2 and α-MSH both have modest BBB penetration; central effects require either high peripheral doses or direct intracranial administration for definitive mechanistic studies",
        "Commercial stability: MT-2 as a lyophilized peptide is stable for >12 months at -20°C; α-MSH is less stable and typically requires more careful handling",
      ],
    },
    {
      type: "heading",
      text: "Emerging Research Directions",
    },
    {
      type: "paragraph",
      text: "Current research with MT-2 and related melanocortin agonists is expanding into several areas:",
    },
    {
      type: "list",
      items: [
        "Neuroprotection: MC4R agonism has shown anti-inflammatory and neuroprotective effects in rodent stroke models (middle cerebral artery occlusion), with MT-2 reducing infarct volume and improving behavioral recovery scores at 0.1–0.3 mg/kg SC in acute post-ischemic windows",
        "Addiction and reward circuitry: MC3R/MC4R in the nucleus accumbens shell modulate dopaminergic tone; MT-2 reduces cocaine-seeking behavior in reinstatement models, suggesting a role in treating substance use disorder",
        "Anti-inflammatory applications: MC4R activation reduces TNF-α, IL-6, and NF-κB activation in macrophage cultures and reduces peritoneal inflammation in rodent models; relevant for inflammatory bowel and systemic inflammatory models",
        "Photocarcinogenesis protection: the combination of UV-DNA damage protection (reduced CPD formation) and immune surveillance enhancement (MC4R on dendritic cells) is being explored as a potential non-human primate model for photocarcinogenesis prevention",
      ],
    },
    {
      type: "callout",
      text: "MT-2 is a research peptide supplied by Nexphoria for licensed researchers and research institutions only. It is not approved for human use, is not a drug or supplement, and must not be administered to humans outside of registered clinical trials. All in vivo research requires IACUC/ethics committee approval.",
    },
    {
      type: "heading",
      text: "Research Summary",
    },
    {
      type: "paragraph",
      text: "Melanotan II is a pharmacologically versatile melanocortin research tool with well-characterized receptor binding (MC1R >> MC4R ≥ MC3R > MC5R), documented in vivo dose-response relationships across melanogenesis, metabolic, and behavioral endpoints, and published pharmacokinetic data from both rodent and human Phase 1/2 studies. Its primary research value lies in studying MC1R-mediated photoprotection/melanogenesis, MC4R-mediated energy balance and autonomic function, and broader melanocortin circuitry modulation in CNS behavioral paradigms.",
    },
    {
      type: "paragraph",
      text: "Researchers should select doses based on target receptor engagement (0.1 mg/kg for selective behavioral endpoints; 0.3 mg/kg for combined metabolic + behavioral; ≤0.03 mg/kg if minimizing MC1R activation is required), include SHU9119 antagonist controls, monitor melanogenesis as a confound in longer-term studies, and use albino strains when visual behavioral scoring would be affected by coat pigmentation changes.",
    },
    {
      type: "disclaimer",
      text: "Nexphoria supplies research-grade MT-2 for licensed researchers. This compound is not intended for personal use, self-administration, or any therapeutic application. All research use must comply with applicable institutional, IACUC, and regulatory requirements.",
    },
  ],
};
