import type { BlogArticle } from '../blog-types';

export const article: BlogArticle = {
  slug: "peptide-research-beginners-first-order-complete-checklist-2026",
  title: "First Research Peptide Order: The Complete Beginner's Checklist (2026)",
  description:
    "Placing your first peptide research order? This step-by-step checklist covers everything from choosing a compound to evaluating suppliers, verifying certificates of analysis, and setting up proper storage — so your research starts on solid footing.",
  category: "Getting Started",
  readMinutes: 9,
  publishedAt: "2026-06-14",
  ogImage: "/og-image.jpg",
  body: [
    {
      type: "paragraph",
      text: "The peptide research space can be overwhelming for first-time researchers. With hundreds of compounds available, dozens of vendors, and a maze of terminology around purity, certificates of analysis, and administration routes — knowing where to start is the real challenge. This checklist is designed to walk you through every step of placing your first order, so you don't discover a critical mistake after your experiment is already underway.",
    },
    {
      type: "heading",
      text: "Step 1: Define Your Research Objective",
    },
    {
      type: "paragraph",
      text: "Before selecting a compound, define the specific biological question your research aims to answer. Peptide selection follows from research design — not the other way around. Common starting research categories and their corresponding well-studied entry-level compounds:",
    },
    {
      type: "table",
      headers: ["Research Category", "Well-Studied Entry Compounds", "Why These First"],
      rows: [
        ["Tissue repair / musculoskeletal", "BPC-157, TB-500", "Extensive preclinical literature; predictable dosing windows; well-documented safety profile in rodent models"],
        ["Growth hormone axis", "Ipamorelin + CJC-1295 (no DAC)", "Selective GH secretagogues; well-characterized pulsatile GH response; widely reproduced results across labs"],
        ["Metabolic / weight loss", "Semaglutide, AOD-9604", "Robust phase 2-3 data (semaglutide); clear mechanism; dose-response well characterized"],
        ["Longevity / anti-aging", "Epithalon, GHK-Cu, NAD+", "High safety margin; mechanistic data on telomere biology and epigenetic reprogramming; accessible starting doses"],
        ["Immune modulation", "Thymosin Alpha-1, KPV", "Well-documented T-cell effects; relevant to immune senescence research; low receptor-level complexity"],
        ["Cognitive / nootropic", "Selank, Semax", "Documented CNS effects; favorable rodent tolerability; clear anxiolytic and cognitive endpoints"],
      ],
    },
    {
      type: "heading",
      text: "Step 2: Understand the Legal and Regulatory Context",
    },
    {
      type: "paragraph",
      text: "In the United States, research peptides sold by legitimate vendors are offered strictly for in vitro and preclinical in vivo research purposes. They are not regulated as drugs by the FDA when sold under these conditions. Key points for new researchers:",
    },
    {
      type: "list",
      items: [
        "Research peptides are legal to purchase in the US for legitimate research use",
        "They must NOT be labeled or sold for human consumption — reputable vendors include explicit 'for research use only' language on all products and invoices",
        "Some peptides are Schedule III controlled substances (e.g., certain steroids are not peptides, but note: TB-500 is not scheduled; BPC-157 is not scheduled; semaglutide is not scheduled)",
        "WADA-prohibited status is separate from legal status — compounds like ipamorelin are WADA-prohibited for professional athletes but not controlled substances",
        "Import restrictions vary by country — US researchers generally have clear legal standing; EU researchers should verify country-specific rules",
      ],
    },
    {
      type: "heading",
      text: "Step 3: Evaluate the Supplier Before You Order",
    },
    {
      type: "paragraph",
      text: "Supplier quality is the single biggest variable in peptide research. A 99.5% pure compound and a 89% pure compound with the same name are not the same material. Before placing your first order, verify:",
    },
    {
      type: "subheading",
      text: "Mandatory Checks",
    },
    {
      type: "list",
      items: [
        "HPLC Certificate of Analysis (COA) — available publicly for each product, batch-specific, showing ≥98% purity (99%+ preferred for research use)",
        "Mass spectrometry (MS) confirmation — confirms the compound identity matches what's labeled; HPLC alone cannot rule out a different peptide at the same purity",
        "Limulus Amebocyte Lysate (LAL) endotoxin testing — confirms the product is endotoxin-free, critical for any in vivo work",
        "Third-party testing — COA generated by an independent lab, not the supplier's own QC department",
        "Batch number traceability — your product's COA should match the batch number on the vial, verifiable on request",
      ],
    },
    {
      type: "subheading",
      text: "Green Flags",
    },
    {
      type: "list",
      items: [
        "COAs downloadable directly from product pages, no inquiry required",
        "Explicit cold-chain shipping policies with insulated packaging and temperature indicators",
        "Clear 'research use only' labeling on all products and correspondence",
        "Domestic US warehouse with 2-day or faster shipping available",
        "Responsive customer service with documented knowledge of the compounds they sell",
      ],
    },
    {
      type: "subheading",
      text: "Red Flags",
    },
    {
      type: "list",
      items: [
        "COA 'available upon request' — legitimate suppliers publish them upfront",
        "HPLC results below 98% purity presented as acceptable",
        "No endotoxin testing documentation",
        "Prices dramatically below market (typically a sign of lower synthesis quality or underdosed vials)",
        "Marketing language implying human use or health benefits",
        "No physical address or customer service contact",
      ],
    },
    {
      type: "heading",
      text: "Step 4: Understand What You're Ordering",
    },
    {
      type: "paragraph",
      text: "Before completing your order, confirm these details for each compound:",
    },
    {
      type: "list",
      items: [
        "Vial size (typically 2mg, 5mg, or 10mg) — buy only what you'll use within a reasonable timeframe to minimize freeze-thaw cycles",
        "Form — lyophilized (freeze-dried powder) is standard; avoid liquid pre-mixed peptides from unknown suppliers as stability is inferior",
        "Reconstitution solvent needed — most peptides use bacteriostatic water (BW) or sterile saline; a few require 0.6% acetic acid (GHK-Cu, some GH-related peptides)",
        "Concentration you'll prepare — determine your working concentration before ordering to make sure your syringe size is appropriate",
        "Shipping requirements — does this compound need cold-chain? (Most do for long transit or summer months)",
      ],
    },
    {
      type: "heading",
      text: "Step 5: Assemble Your Research Supplies",
    },
    {
      type: "paragraph",
      text: "You'll need more than the peptide itself. First-time researchers often overlook these essentials:",
    },
    {
      type: "list",
      items: [
        "Bacteriostatic water (BW) — for reconstitution; 30 mL vials are standard; ensure it's sterile and bacteriostatic (contains 0.9% benzyl alcohol)",
        "Insulin syringes — U-100 (100 units/mL) are standard for peptide administration in research; needle gauge 28–31G for subcutaneous in rodent models",
        "Alcohol swabs — for vial top sterilization before drawing",
        "A fine-point lab marker — for labeling vials with compound name, concentration, and date of reconstitution",
        "A mini-fridge or dedicated section of your lab fridge at 4°C for reconstituted peptides",
        "A -20°C freezer for long-term storage of unreconstituted vials",
        "A lab notebook or digital logging system — record every batch number, reconstitution date, concentration, and storage location",
      ],
    },
    {
      type: "heading",
      text: "Step 6: Reconstitution Protocol",
    },
    {
      type: "paragraph",
      text: "Reconstitution is where many first-time researchers make irreversible mistakes. Follow this protocol:",
    },
    {
      type: "list",
      items: [
        "Allow the peptide vial to reach room temperature before opening — prevents condensation from forming inside the vial",
        "Wipe the rubber stopper of both the peptide vial and the BW vial with an alcohol swab; allow to air dry 30 seconds",
        "Draw the required volume of BW into your syringe (calculate based on desired concentration)",
        "Inject BW into the peptide vial slowly, aiming the stream at the inside glass wall — do not shoot directly at the lyophilized cake",
        "Gently swirl (do not shake or vortex) until the powder is fully dissolved — peptides are fragile and mechanical agitation can cause aggregation",
        "The solution should be clear and colorless (slight tint is acceptable for some compounds like GHK-Cu, which is blue)",
        "Label the vial immediately with compound, concentration, date, and your initials",
      ],
    },
    {
      type: "heading",
      text: "Step 7: Storage and Shelf Life Reference",
    },
    {
      type: "table",
      headers: ["State", "Temperature", "Expected Shelf Life", "Notes"],
      rows: [
        ["Lyophilized (sealed)", "-20°C", "12–24 months", "Store with desiccant in light-blocking container"],
        ["Lyophilized (opened/reconstituted)", "4°C", "14–30 days depending on compound", "Varies significantly; follow compound-specific guidance"],
        ["Reconstituted", "-20°C", "Not recommended for most peptides", "Freeze-thaw degrades most reconstituted peptides; avoid"],
        ["Reconstituted at room temp", "Ambient", "Hours only", "Never store reconstituted peptides at room temperature"],
      ],
    },
    {
      type: "heading",
      text: "Step 8: Document Everything",
    },
    {
      type: "paragraph",
      text: "Research reproducibility depends on documentation. For every peptide in your protocol, log:",
    },
    {
      type: "list",
      items: [
        "Supplier name and order confirmation number",
        "Batch/lot number from the vial",
        "COA purity value and test date",
        "Date received and visual inspection notes",
        "Date reconstituted and working concentration prepared",
        "Volume withdrawn per administration and administration dates/times",
        "Any anomalies (cloudiness, unexpected color, solubility issues)",
      ],
    },
    {
      type: "callout",
      text: "Pro Tip: Keep a photo of each vial's label and COA alongside your lab notes. When you're analyzing data months later, you'll want to be able to trace any anomalous results back to a specific batch.",
    },
    {
      type: "heading",
      text: "Where to Start with Nexphoria",
    },
    {
      type: "paragraph",
      text: "Nexphoria provides batch-specific HPLC, mass spectrometry, and LAL endotoxin certificates for every compound — downloadable directly from each product page before purchase. Cold-chain shipping is standard, not a premium add-on. For first-time researchers, the BPC-157, Ipamorelin, and GHK-Cu product pages each include detailed sourcing and handling notes alongside their certificates of analysis.",
    },
    {
      type: "divider",
    },
    {
      type: "disclaimer",
      text: "For research purposes only. Not intended for human use. All peptide compounds referenced are sold strictly for in vitro and preclinical research applications.",
    },
  ],
};
