import type { BlogArticle } from '../blog-types';

export const article: BlogArticle = {
  slug: "ss-31-elamipretide-mitochondria-peptide-research-jun21-2026",
  title: "SS-31 (Elamipretide): Mitochondria-Targeted Peptide Research Guide (2026)",
  description:
    "A comprehensive research overview of SS-31 (Elamipretide / MTP-131) — the tetrapeptide that targets the inner mitochondrial membrane. What preclinical and early clinical studies show about cardiolipin binding, mitochondrial function, and aging research.",
  category: "Compound Profiles",
  readMinutes: 10,
  publishedAt: "2026-06-21",
  ogImage: "/og-image.jpg",
  body: [
    {
      type: "paragraph",
      text: "SS-31 — also known as Elamipretide, MTP-131, and Bendavia — is a tetrapeptide belonging to the Szeto-Schiller (SS) family of mitochondria-targeted compounds. Its sequence (D-Arg-Dmt-Lys-Phe-NH₂) incorporates a dimethyltyrosine (Dmt) residue that confers affinity for the inner mitochondrial membrane, making it one of the few peptides in research designed specifically to accumulate within the mitochondrion itself rather than acting from the cytoplasm or extracellular space.",
    },
    {
      type: "heading",
      text: "What Is SS-31?",
    },
    {
      type: "paragraph",
      text: "SS-31 was developed by Hazel Szeto and colleagues at Cornell University as part of a broader program to engineer peptides capable of crossing mitochondrial membranes and modulating bioenergetic function. The compound carries a net positive charge at physiological pH, which facilitates electrostatic interaction with the negatively charged inner mitochondrial membrane (IMM) — enabling it to reach the matrix side at concentrations 1,000-fold higher than in the cytoplasm.",
    },
    {
      type: "list",
      items: [
        "Sequence: D-Arg-Dmt-Lys-Phe-NH₂",
        "Molecular weight: ~639 Da",
        "Key feature: Cationic aromatic structure with high IMM selectivity",
        "Primary target: Cardiolipin — a phospholipid critical to mitochondrial cristae architecture",
        "Administration in research: Subcutaneous or intravenous in animal models; IV in human trials",
      ],
    },
    {
      type: "heading",
      text: "Mechanism of Action",
    },
    {
      type: "subheading",
      text: "Cardiolipin Interaction",
    },
    {
      type: "paragraph",
      text: "The primary proposed mechanism of SS-31 centers on its interaction with cardiolipin — a unique phospholipid found almost exclusively in the inner mitochondrial membrane. Cardiolipin plays a structural role in maintaining cristae architecture and a functional role in supporting the electron transport chain (ETC) complexes, particularly Complex I, III, and IV. During oxidative stress or aging, cardiolipin undergoes peroxidation, which disrupts ETC function and increases reactive oxygen species (ROS) production. SS-31 binds cardiolipin and is proposed to inhibit its peroxidation, thereby stabilizing ETC complex assembly and reducing electron leak.",
    },
    {
      type: "subheading",
      text: "ATP Synthesis Enhancement",
    },
    {
      type: "paragraph",
      text: "Multiple preclinical studies have documented improved ATP production in SS-31-treated tissue following ischemic or hypoxic insult. This effect is attributed to the restoration of cristae structure — which brings ATP synthase (Complex V) into closer proximity with the proton gradient generated by the ETC — and the reduction of ROS-mediated Complex I inhibition.",
    },
    {
      type: "subheading",
      text: "Mitophagy and Quality Control",
    },
    {
      type: "paragraph",
      text: "Emerging research has linked SS-31 to improvements in mitochondrial quality control pathways, including PINK1/Parkin-mediated mitophagy — the selective clearance of damaged mitochondria. In models of sarcopenia and cardiac aging, SS-31 treatment has been associated with reduced accumulation of dysfunctional mitochondria, though the mechanistic basis for this remains under investigation.",
    },
    {
      type: "heading",
      text: "Key Research Findings",
    },
    {
      type: "subheading",
      text: "Cardiac and Ischemia-Reperfusion Models",
    },
    {
      type: "paragraph",
      text: "The most robust body of SS-31 preclinical research involves cardiac protection during ischemia-reperfusion (I/R) injury. Studies in rat and pig models have consistently shown reduced infarct size, improved left ventricular function, and attenuated cardiomyocyte apoptosis when SS-31 is administered prior to or at the time of reperfusion. These findings drove the compound into Phase II/III clinical trials under the name Elamipretide for heart failure and Barth syndrome, a rare genetic disorder characterized by cardiolipin abnormalities.",
    },
    {
      type: "subheading",
      text: "Skeletal Muscle and Sarcopenia",
    },
    {
      type: "paragraph",
      text: "Researchers have investigated SS-31 in models of age-related skeletal muscle loss (sarcopenia). Studies in old mice and rats have documented improvements in muscle fiber size, grip strength, and mitochondrial respiration following SS-31 treatment. Siegel et al. (2013) demonstrated that 8 weeks of SS-31 in aged mice reversed approximately 30% of the age-related decline in mitochondrial coupling efficiency as measured by respirometry — a notable finding for aging biology researchers.",
    },
    {
      type: "subheading",
      text: "Kidney and Renal Research",
    },
    {
      type: "paragraph",
      text: "Renal ischemia-reperfusion models have shown SS-31 to reduce tubular injury markers, preserve GFR, and attenuate fibrosis in the context of acute kidney injury. This body of work has supported investigation of SS-31 in clinical kidney disease contexts, including acute kidney injury during cardiac surgery.",
    },
    {
      type: "subheading",
      text: "Neurodegenerative Models",
    },
    {
      type: "paragraph",
      text: "Given that mitochondrial dysfunction is implicated in Alzheimer's, Parkinson's, and ALS pathology, SS-31 has been studied in relevant preclinical models. In APP/PS1 transgenic mouse models of Alzheimer's, SS-31 treatment has been associated with reduced amyloid burden, improved synaptic density, and better performance on spatial memory tasks. In 6-OHDA models of Parkinson's, SS-31 showed protection of dopaminergic neurons. These findings are preliminary and limited to animal models.",
    },
    {
      type: "heading",
      text: "SS-31 vs. Other Mitochondrial Peptides",
    },
    {
      type: "table",
      headers: ["Peptide", "Primary Target", "Key Research Application", "Administration Route"],
      rows: [
        ["SS-31 (Elamipretide)", "Cardiolipin / IMM", "Cardiac, renal, sarcopenia, neurodegeneration", "SC / IV"],
        ["MOTS-c", "AMPK / nuclear stress response", "Metabolic regulation, exercise mimetic", "SC / IV"],
        ["Humanin", "IGF-1R / STAT3 / FPRL2", "Neuroprotection, apoptosis inhibition", "SC / IV / intranasal"],
        ["SS-20 (related)", "Cardiolipin (antioxidant)", "Cardiac preclinical", "IV"],
      ],
    },
    {
      type: "heading",
      text: "Clinical Status",
    },
    {
      type: "paragraph",
      text: "Elamipretide (SS-31) has been evaluated in multiple clinical trials. The EMBRACE-HF study (Phase II, ~2019) demonstrated improvements in 6-minute walk distance and heart failure biomarkers with subcutaneous elamipretide in patients with HFrEF, though Phase III results have been mixed. In Barth syndrome — where cardiolipin remodeling enzyme deficiency is the primary defect — elamipretide showed meaningful clinical signals. As of 2026, research continues under Stealth BioTherapeutics (now part of Minovia Therapeutics) and academic groups.",
    },
    {
      type: "callout",
      text: "Note: SS-31 is classified as a research peptide in the United States. It is not FDA-approved for any indication. The clinical data referenced here reflects investigational trials. Research use is subject to institutional IRB/IACUC oversight.",
    },
    {
      type: "heading",
      text: "Dosing in Preclinical Research",
    },
    {
      type: "paragraph",
      text: "The following reflects doses used in preclinical models only. These are not clinical recommendations.",
    },
    {
      type: "table",
      headers: ["Model", "Route", "Dose Range", "Duration"],
      rows: [
        ["Mouse (aging/sarcopenia)", "SC injection", "3–5 mg/kg/day", "4–8 weeks"],
        ["Rat (cardiac I/R)", "IV bolus", "1–3 mg/kg", "Single dose at reperfusion"],
        ["Mouse (Alzheimer's model)", "SC", "5 mg/kg/day", "8–12 weeks"],
        ["Pig (cardiac surgery)", "IV infusion", "0.05–0.25 mg/kg/hr", "During procedure"],
      ],
    },
    {
      type: "heading",
      text: "Sourcing SS-31 for Research",
    },
    {
      type: "paragraph",
      text: "SS-31 is synthesized as a custom peptide by specialty manufacturers. For research applications, purity and endotoxin testing are critical — particularly for in vivo studies where endotoxin contamination can confound results and trigger immune responses.",
    },
    {
      type: "list",
      items: [
        "HPLC purity: Minimum ≥98% for in vitro applications; ≥99% recommended for in vivo rodent models",
        "Mass spectrometry (MS): Required to confirm D-amino acid incorporation and Dmt residue identity",
        "LAL endotoxin testing: Essential for any injectable research use",
        "Lyophilized form: Preferred for long-term stability; reconstitute in sterile saline or water for injection",
        "Storage: -20°C dry, protected from light; reconstituted solution should be used within 7 days or aliquoted and re-frozen once",
      ],
    },
    {
      type: "heading",
      text: "Summary: What Researchers Should Know",
    },
    {
      type: "paragraph",
      text: "SS-31 (Elamipretide) represents one of the most mechanistically specific research peptides available — a compound designed from first principles to target the inner mitochondrial membrane and modulate cardiolipin-dependent bioenergetics. Its preclinical record across cardiac, renal, skeletal muscle, and neurological models is among the strongest of any mitochondria-targeted compound. Clinical translation has been challenging but ongoing. For researchers investigating mitochondrial aging, cardiac ischemia, sarcopenia, or neurodegenerative biology, SS-31 remains a high-interest tool compound.",
    },
    {
      type: "disclaimer",
      text: "All information presented is for educational and research purposes only. SS-31/Elamipretide is not approved for human use outside of clinical trials. This content does not constitute medical advice.",
    },
  ],
};
